default_settings:
  trainer_type: ppo
<<<<<<< HEAD
  summary_freq: 50000
  max_steps: 20000000
  checkpoint_interval: 20000000
=======
  summary_freq: 0
  max_steps: 4107595
  checkpoint_interval: 500000
>>>>>>> 38d21957edce1973d69fc0f43461716e887dbf86
  keep_checkpoints: 5
  time_horizon: 64
  threaded: true
  hyperparameters:
<<<<<<< HEAD
    batch_size: 2048
    buffer_size: 16384
    learning_rate: 0.00035
=======
    batch_size: 256
    buffer_size: 10240
    learning_rate: 0.000527
>>>>>>> 38d21957edce1973d69fc0f43461716e887dbf86
    learning_rate_schedule: linear
    beta: 0.005
    epsilon: 0.2
    lambd: 0.95
    num_epoch: 3
  network_settings:
    hidden_units: 113
    num_layers: 2
    vis_encode_type: match3
checkpoint_settings:
  results_dir: Results
  run_id: mlady-medium-4
  initialize_from: mlady-medium-4
  resume: false
  force: true
engine_settings:
  time_scale: 2
  quality_level: 1
torch_settings:
  device: cuda
