default_settings:
  trainer_type: ppo
  summary_freq: 1000
  max_steps: 5000000
  checkpoint_interval: 5000000
  keep_checkpoints: 5
  time_horizon: 64
  threaded: true
  hyperparameters:
    batch_size: 256
    buffer_size: 10240
    learning_rate: 0.0003
    learning_rate_schedule: linear
    beta: 0.005
    epsilon: 0.2
    lambd: 0.95
    num_epoch: 3
  network_settings:
    hidden_units: 128
    num_layers: 2
    vis_encode_type: simple
    normalize: false
checkpoint_settings:
  results_dir: Results
  run_id: mlady
  force: true
engine_settings:
  time_scale: 1
  quality_level: 5
torch_settings:
  device: cuda
