default_settings:
  trainer_type: ppo
  summary_freq: 25000
  max_steps: 500000
  checkpoint_interval: 10000000
  keep_checkpoints: 5
  time_horizon: 64
  threaded: true
  hyperparameters:
    batch_size: 2048
    buffer_size: 16384
    learning_rate: 0.0005
    learning_rate_schedule: linear
    beta: 0.005
    epsilon: 0.2
    lambd: 0.95
    num_epoch: 10
  network_settings:
    hidden_units: 128
    num_layers: 2
    vis_encode_type: match3
checkpoint_settings:
  results_dir: Results
  run_id: mlady-rc-scale
  initialize_from: mlady-rc-scale
  resume: false
  force: true
engine_settings:
  time_scale: 5
  quality_level: 5
torch_settings:
  device: cuda
